In [6]:
#Create a NumPy array of shape (3,3) filled with ones.
import numpy as np

array = np.ones((3,3))
print (array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
import numpy as np

random_array = np.random.rand(3,3)

print(random_array)

[[0.47292786 0.87181867 0.56718154]
 [0.50322893 0.783348   0.32842613]
 [0.08649001 0.44016351 0.29169315]]


In [13]:
import numpy as np
# Generate 10 values evenly spaced between 10 and 100
array = np.arange(10, 110, 10)

print(array)

# Generate 10 random integers between 10 and 100
random_int_array = np.random.randint(10, 101, size=10)

print(random_int_array)

[ 10  20  30  40  50  60  70  80  90 100]
[12 18 51 86 76 37 82 76 73 47]


In [16]:
import numpy as np

# Create a 1D array with 10 elements
array = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]

# Reshape it into (2,5)
reshaped_array = array.reshape(2, 5)

print(reshaped_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]
----------------------------------
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
import numpy as np

# Create a NumPy array
array = np.array([10, 20, 30, 40, 50])

# Compute statistical values
mean_value = np.mean(array)         # Mean
max_value = np.max(array)           # Maximum value
min_value = np.min(array)           # Minimum value
std_dev = np.std(array)             # Standard deviation

# Print results
print(f"Mean: {mean_value}")
print(f"Max: {max_value}")
print(f"Min: {min_value}")
print(f"Standard Deviation: {std_dev}")

Mean: 30.0
Max: 50
Min: 10
Standard Deviation: 14.142135623730951
